apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: staging
  labels:
   env: stage  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: stage 
  template:
    metadata:
      labels:
        app: nginx
        env: stage 
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
