apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stage
  namespace: nginx-stage
  labels:
   env: stage  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-stage
      env: stage 
  template:
    metadata:
      labels:
        app: nginx-stage
        env: stage 
    spec:
      containers:
        - name: nginx-stage
          image: nginx:latest
          ports:
            - containerPort: 80
